name: Docker Image CI

on:
  push:
    branches: ["deploy"]
  pull_request:
    branches: ["deploy"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout source
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-image-name:latest .

      # Run Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name my-app my-image-name:latest
